version: "3"
services:
  master:
    container_name: master
    image: jenkinsci/jenkins:2.142-slim
    ports:
      - 8081:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
    links:
      - slave01

  slave01:
    container_name: slave01
    image: jenkinsci/ssh-slave
    environment:
      # 本来であれば、以下にjenkins_home/.ssh/id_rsa.pubに指定の公開鍵を指定する
      # 今回は省略
      # - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa
